SYSTEM_USERNAME = 'your system username'

GMAIL_USERNAME = 'username'
GMAIL_PASSWORD = 'pass'

TWILIO_ACCOUNT_SID = 'YOUR TWILIO ACCOUNT SID'
TWILIO_AUTH_TOKEN = 'YOUR TWILIO ACCOUNT TOKEN'

PHONEBOOK = {
    'ME': 'YOUR PHONE NUM',
    'WIFE': 'WIFE\'S PHONE NUM',
    'BOSS': 'BOSS\' PHONE NUM',
}

EMAIL_CONTACTS = {
    'KUMAR': 'KUMAR\'S EMAIL',
}
